### ISSUE TITLE
Docker Image is throwing Exceptions in Runtime

### ISSUE THREAD

**Issue by Mohithraj916** [frumania/docker-uiveri5-jenkins-slave#2]
The docker image is throwing exceptions when we try to start selenium server.

![Selenium server start Issue](https://user-images.githubusercontent.com/36323835/126939775-4eaedb81-a7de-423e-9644-f67fb5c9d42e.PNG)

After removing -browserSideLog argument from startSelenium.sh file the selenium server started but getting error in executing next command : docker exec myslave uiveri5 --v --seleniumAddress http://localhost:4444/wd/hub ...

![Selenium localserver issue](https://user-images.githubusercontent.com/36323835/126940040-34ba377c-92d7-4c88-b143-7fa3dbf74c8b.PNG)

When removed ... from command: docker exec myslave uiveri5 --v --seleniumAddress http://localhost:4444/wd/hub ... 
It resulted in git repo issue.

![Selenium local server issue](https://user-images.githubusercontent.com/36323835/126940264-8a73c3aa-1b88-4e91-b264-e706b4d9f3ab.PNG)

Any methods to fix these issues?

**Comment by Mohithraj916** [comment]
Can you help me with steps to execute spec files, do we need to have spec files in same directory / docker image? and also is there any way to authenticate application using configuration which is under test.
Please let me know about these username and password variables 
--config "{\"auth\": {\"sapcloud-form\": {\"user\": \"$user\",\"pass\": \"$password\"}}}"

**Comment by frumania** [comment]
Hey,

you basically need to copy/share the test.spec.js + conf.js with the docker container. Or in my case the whole "test" folder.

For example in folder "docker-uiveri5-jenkins-slave" execute

  - docker run --name myslave -v $PWD:/test/ -dit uiveri5-base:latest /bin/bash
  - sleep 10
  - docker ps
  - docker exec -d myslave /opt/selenium/startSeleniumServer.sh
  - sleep 10
  - docker exec -d myslave bash -c "cd /test/test && ./test1.sh"
  - sleep 60

@Authentication (for example FLP), see here:
https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/authentication.md
